[phases.setup]
nixPkgs = ['nodejs-20_x', 'pnpm']

[phases.install]
<<<<<<< HEAD
cmds = [
  'pnpm install --frozen-lockfile',
  'pnpm prisma generate'
]

[phases.build]
cmds = [
  'pnpm prisma generate',
  'pnpm run build'
]

[start]
cmd = 'node --max-old-space-size=512 dist/main'

[variables]
PORT = '3000'
NODE_ENV = 'production'
=======
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'pnpm run start:prod'
>>>>>>> 9e7ed34722035ce8c5e304e50c0ff830bf2359f3
